# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: the.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='the.proto',
  package='queryDouBanID',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tthe.proto\x12\rqueryDouBanID\"\x1b\n\x0bIsbnRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"\x19\n\nIdUrlReply\x12\x0b\n\x03url\x18\x01 \x01(\t2K\n\x07QueryID\x12@\n\x05Query\x12\x1a.queryDouBanID.IsbnRequest\x1a\x19.queryDouBanID.IdUrlReply\"\x00\x62\x06proto3')
)




_ISBNREQUEST = _descriptor.Descriptor(
  name='IsbnRequest',
  full_name='queryDouBanID.IsbnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isbn', full_name='queryDouBanID.IsbnRequest.isbn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=55,
)


_IDURLREPLY = _descriptor.Descriptor(
  name='IdUrlReply',
  full_name='queryDouBanID.IdUrlReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='queryDouBanID.IdUrlReply.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['IsbnRequest'] = _ISBNREQUEST
DESCRIPTOR.message_types_by_name['IdUrlReply'] = _IDURLREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IsbnRequest = _reflection.GeneratedProtocolMessageType('IsbnRequest', (_message.Message,), {
  'DESCRIPTOR' : _ISBNREQUEST,
  '__module__' : 'the_pb2'
  # @@protoc_insertion_point(class_scope:queryDouBanID.IsbnRequest)
  })
_sym_db.RegisterMessage(IsbnRequest)

IdUrlReply = _reflection.GeneratedProtocolMessageType('IdUrlReply', (_message.Message,), {
  'DESCRIPTOR' : _IDURLREPLY,
  '__module__' : 'the_pb2'
  # @@protoc_insertion_point(class_scope:queryDouBanID.IdUrlReply)
  })
_sym_db.RegisterMessage(IdUrlReply)



_QUERYID = _descriptor.ServiceDescriptor(
  name='QueryID',
  full_name='queryDouBanID.QueryID',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=84,
  serialized_end=159,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='queryDouBanID.QueryID.Query',
    index=0,
    containing_service=None,
    input_type=_ISBNREQUEST,
    output_type=_IDURLREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERYID)

DESCRIPTOR.services_by_name['QueryID'] = _QUERYID

# @@protoc_insertion_point(module_scope)
